---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/login/{name}":
    get:
      summary: login user
      tags:
      - Login
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                - token
  "/v1/register":
    post:
      summary: register user
      responses:
        '200':
          description: registration successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
